language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - phpunit

notifications:
  irc: "irc.freenode.org#zftalk.modules"
  email: false
